# Configuration inspired by Ricardo Mendes
# Original repository: ricardolsmendes/gcp-cloudbuild-gae-angular

runtime: python27
api_version: 1
threadsafe: yes

# Google App Engine's cache default expiration time is 10 minutes. It's suitable for most Production
# scenarios, but a shorter TTL may be desired for Development and QA, as it allows us to see a fresh
# code in action just a minute after the deployment.
# default_expiration: 60s

handlers:
  - url: /(.+\.js)
    static_files: dist/\1
    upload: dist/(.+\.js)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.css)
    static_files: dist/\1
    upload: dist/(.+\.css)
    secure: always
    redirect_http_response_code: 301

  - url: /assets/(.+\.png)
    static_files: dist/\1
    upload: dist/assets/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.png)
    static_files: dist/\1
    upload: dist/(.+\.png)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.jpg)
    static_files: dist/\1
    upload: dist/(.+\.jpg)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.gif)
    static_files: dist/\1
    upload: dist/(.+\.gif)
    secure: always
    redirect_http_response_code: 301
    
  - url: /(.+\.tff)
    static_files: dist/\1
    upload: dist/(.+\.tff)
    secure: always
    redirect_http_response_code: 301
    
  - url: /(.+\.eot)
    static_files: dist/\1
    upload: dist/(.+\.eot)
    secure: always
    redirect_http_response_code: 301
    
  - url: /(.+\.woff2)
    static_files: dist/\1
    upload: dist/(.+\.woff2)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.svg)
    static_files: dist/\1
    upload: dist/(.+\.svg)
    secure: always
    redirect_http_response_code: 301

  - url: /favicon.ico
    static_files: dist/favicon.ico
    upload: dist/favicon.ico
    secure: always
    redirect_http_response_code: 301

  - url: /(.+\.json)
    static_files: dist/\1
    upload: dist/(.+\.json)
    secure: always
    redirect_http_response_code: 301

  - url: /(.+)
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    redirect_http_response_code: 301

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE
